### ISSUE TITLE
Error when running script - Illegal token

### ISSUE THREAD

**Issue by cloudlady911** [heedsoftware/auto-assign-elastic-ip#1]
I set everything up but I get this error:

```
Instance Region: us-west-2.
Instance Environment: Web5.
Illegal token value '?AssociationId==null].AllocationId'
Failed to assign EIP. Pausing for 5 seconds before retrying...
```
Instance tags: Environment=Web5, Name=Web5
EIP tags: Environment=Web5, Name=Web5

Running on Ubuntu 14.04.  (Yeah, I know, but I am stuck with it)

I was able to get this to work just fine on Ubuntu 16.  But I really need it to work on Ubuntu 14

**Comment by allens01** [comment]
Hi @cloudlady911 

I have tried to run the script on 14.04 and it run successfully for me. What happens if you run this command directly on the server?

aws ec2 describe-addresses --region us-west-2 --filters "Name=tag:Environment,Values=Web5" --query "Addresses[?AssociationId==null].AllocationId" --output text

**Comment by cloudlady911** [comment]
Thanks for your response @allens01! I get the same error when running it locally.  Is it maybe case sensitive?  I will try with lowercase tags and see if I get a different result.

**Comment by cloudlady911** [comment]
No.  Changing the case does not matter.  I deleted and recreated the tags in case there was some hidden character. but still no luck.
I also tried with a newly allocated EIP.

**Comment by cloudlady911** [comment]
I think I found the problem.  I installed the awscli with apt-get.  It did not install the latest version.  I installed the latests version and it works fine now. 

This was the installation method I used:
`curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"

unzip awscli-bundle.zip

sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws`
