### ISSUE TITLE
Error handling L55

### ISSUE THREAD

**Issue by strudelPi** [heedsoftware/auto-assign-elastic-ip#2]
The error handling on this line produces following error:

`Attempting to assign Elastic IP to instance...
/root/auto-assign-elastic-ip.sh: line 55: exit_code: command not found`

fixed it by following replacement:
```
-       if ! exit_code; then
+       if [ "$exit_code" -ne 0 ]; then
```

**Comment by allens01** [comment]
Great, thanks @strudelPi, I have updated
